const CUSTOM_EPOCH = 1609459200000; // January 1st 2021 12:00:00 AM
const EPOCH_BITS = 41;
const NODE_ID_BITS = 10;
const MAX_NODE_ID = Math.pow(2, NODE_ID_BITS) - 1;
const SEQUENCE_BITS = 13;
const MAX_SEQUENCE_ID = Math.pow(2, SEQUENCE_BITS) - 1;

module.exports = {
  CUSTOM_EPOCH,
  EPOCH_BITS,
  NODE_ID_BITS,
  MAX_NODE_ID,
  SEQUENCE_BITS,
  MAX_SEQUENCE_ID,
};
